Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'IE',false,true,true,'','Ireland');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'ES',false,true,true,'','Spain');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'CH',false,true,true,'','Switzerland');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'AU',false,true,true,'','Australia');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'AE',false,true,true,'','United Arab Emirates');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'BE',false,true,true,'','Belgium');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'AT',false,true,true,'','Austria');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'ZA',false,true,true,'','South Africa');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'MX',false,true,true,'','Mexico');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'SJ',false,true,true,'','Svalbard and Jan Mayen');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'NL',false,true,true,'','Netherlands');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'AX',false,true,true,'','Aland Islands');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'RU',false,true,true,'','Russian Federation');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'SG',false,true,true,'','Singapore');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'TH',false,true,true,'','Thailand');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'MY',false,true,true,'','Malaysia');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'CN',false,true,true,'','People Republic of China');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'GB',false,true,true,'','United Kingdom');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'LK',false,true,true,'','Sri Lanka');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'DK',false,true,true,'','Denmark');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'IN',false,true,true,'','India');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'SI',false,true,true,'','Slovenia');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'BR',false,true,true,'','Brazil');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'NZ',false,true,true,'','New Zealand');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'FJ',false,true,true,'','Fiji');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'CZ',false,true,true,'','Czech Republic');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'DO',false,true,true,'','Dominican Republic');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'TR',false,true,true,'','Turkey');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'LT',false,true,true,'','Lithuania');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'US',false,true,true,'','United States');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'IT',false,true,true,'','Italy');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'SK',false,true,true,'','Slovakia');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'LU',false,true,true,'','Luxembourg');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'NO',false,true,true,'','Norway');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'FI',false,true,true,'','Finland');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'PL',false,true,true,'','Poland');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'PT',false,true,true,'','Portugal');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'DE',false,true,true,'','Germany');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'CA',false,true,true,'','Canada');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'EE',false,true,true,'','Estonia');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'JP',false,true,true,'','Japan');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'DM',false,true,true,'','Dominica');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'HU',false,true,true,'','Hungary');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'SE',false,true,true,'','Sweden');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'SD',false,true,true,'','Sudan');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'ZM',false,true,true,'','Zambia');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'FR',false,true,true,'','France');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'LV',false,true,true,'','Latvia');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'SZ',false,true,true,'','Swaziland');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'FO',false,true,true,'','Faroe Islands');
Insert into t_country("id","code","fully_compliant","active","white_listed","description","name") values(nextval('t_country_id_seq'),'SR',false,true,true,'','Suriname');
